# Generated by Django 3.2.9 on 2022-06-13 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='summonerId',
            field=models.CharField(max_length=16),
        ),
    ]
